### ISSUE TITLE
If registering multiple RTC event handlers, wrong handler will be used

### ISSUE THREAD

**Issue by ajkitson** [plucky-oatmeal/plucky-oatmeal#43]

**Comment by ajkitson** [comment]
If you have handlers for multiple events, the wrong handlers will be associated with some of the events. That's because this code relies on closure access to `e` to figure out which handler to apply:

```
    for (var e in this.handlers) {
      pc[e] = function () {
        var args = Array.prototype.slice.call(arguments);
        args.push(remoteUser, pc);
        this.handlers[e].apply(undefined, args);
      }.bind(this);
    }
```

`e`'s reference will continue to change with the loop, and when we exit, will be the last event to be considered. We don't notice this when there's just one event, but if there are two or more, all will trigger the handlers of the last event.

**Comment by rjatkinson2** [comment]
See pull request #46 for a fix to this issue.
