### ISSUE TITLE
Allow audience to turn their mics on/off

### ISSUE THREAD

**Issue by ajkitson** [plucky-oatmeal/plucky-oatmeal#44]

**Comment by ajkitson** [comment]
From slack:
andy [9:24 AM] 
We talked on the call about what happens when an audience member pushes the mic on/off button. This shouldn't change the media stream since that would require the entire peer connection to be renegotiated each time. Instead, it's probably best to send a message over the signal server from the audience member to the presenter, letting the presenter know to mute/unmute the audience member. But we don't have support for that type of message in baseRTC.

@rjatkinson2 -- are you up for updating baseRTC to support generic message passing between audience and presenter? (If you want to make it a challenge, you could send the message over an RTC Data Channel instead of via the signal server... probably not worth it, though)

andy [10:46 AM] 
Actually, after thinking about it a bit longer, we may want to open and close the RTC channel each time someone hits the mic on/off button. That way the lecturer is only maintaining a handful of peer connections at any given time, which would be easier on its bandwidth and cpu. That would require updating baseRTC to allow the controller to close the peer connection (the peer connection has a native close method) and notify the presenter that it's closed. Maybe this isn't the way we go for the mvp, but long term we probably want to do it this way.

OK, that's it for me today--off to the trails!

**Comment by rjatkinson2** [comment]
Closed this issue via implementation associated with pull request #50.
